/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoengenhariasoftware;

import java.awt.Desktop;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author aluno
 */
public class AlunoFrmPrincipal extends javax.swing.JFrame {

    BancoDados conexao;
    String nome;
    
    public void setConexao(BancoDados conexao) {
        this.conexao = conexao;
    }

    /**
     * Creates new form FrmPrincipal
     */
    public AlunoFrmPrincipal(BancoDados conexao, String nome) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.nome = nome;
        AlunoTelaUsuario frame = new AlunoTelaUsuario(conexao, nome);
        frame.setConexao(conexao);
        chamarFrame(frame);
        
    }

    public void chamarIFrame(JInternalFrame frame) {
        chamarFrame(frame);
    }

    private void chamarFrame(JInternalFrame frame) {
        centralizaForm(frame);
        frame.setVisible(true);
        jDesktop.add(frame);
        try {
            frame.setSelected(false);
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Enviar certificado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void chamarEnviarCertificado(JInternalFrame frame) {
        centralizaForm(frame);
        frame.setVisible(true);
        jDesktop.add(frame);
        try {
            frame.setSelected(false);
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
        }

    }
    
    public static void chamarVisualiarHora(JInternalFrame frame) {
        centralizaForm(frame);
        frame.setVisible(true);
        jDesktop.add(frame);
        try {
            frame.setSelected(false);
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
        }

    }

    private static void centralizaForm(JInternalFrame frame) {
        Dimension paneSize = frame.getSize();
        Dimension screenSize = frame.getToolkit().getScreenSize();
        frame.setLocation((screenSize.width - paneSize.width) / 2, (int) ((screenSize.height - paneSize.height) / 2.5));
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AlunoTelaEnviarCertificado aluno = new AlunoTelaEnviarCertificado(nome);
        chamarEnviarCertificado(aluno);
        aluno.setConexao(conexao);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
